full_rebuild: true
name: ISYANATION
description: Unite the Isyana Sarasvati lovers!
destination: isyanation
url: https://blog.isyanation.tk
baseurl: #place folder name if site is served in subfolder
permalink: /:title/
paginate: 8
paginate_path: /page/:num/
infinite_scroll: true #change to false if you want to use pagination
gems: [jekyll-paginate]
tag_dir: /tag
category_dir: /category
author_dir: /author
author_title_prefix: 'Diposkan oleh '
media_folder: /media/compressed
author_default_avatar: /profile-pic.jpg
tumblr: "#"
pinterest: "#"
instagram: "isyanation"
twitter: "isyanation"
facebook: "nfiarts"
youtube: "#"
vimeo: "#"
soundcloud: "nfiarts-music"

encoding: utf-8
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post-material-sidebar-left"
      type: "standard"
      homedisplay: "featimg"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
relative_permalinks: false
exclude: [.git, .gitignore, sass, .sass-cache, package.json, gruntfile.js, node_modules, README.md, jekyllbuild]

# prose.io configurations
prose:
  media: "img"
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "layout"
        field:
          element: "select"
          label: "Tampilan"
          help: "Mengubah tampilan utama situs ini"
          options:
            - name: "Dengan sidebar"
              value: "post"
            - name: "Tanpa sidebar"
              value: "post-full"
      - name: "author"
        field:
          element: "text"
          label: "Postingan dari"
          help: "author id as defined within _data/authors.yml"
          type: "text"
      - name: "featimg"
        field:
          element: "text"
          label: "Featured Image"
          help: "featured image within the img-folder"
          type: "text"
      - name: "type"
        field:
          element: "select"
          label: "Tipe Postingan"
          help: "each type has some special feature"
          options:
            - name: "Standard"
              value: "standard"
            - name: "Image"
              value: "image"
            - name: "Gallery"
              value: "gallery"
            - name: "Audio"
              value: "audio"
            - name: "YouTube"
              value: "youtube"
            - name: "Vimeo"
              value: "vimeo"
      - name: "homedisplay"
        field:
          element: "select"
          label: "Home Display"
          help: "decide whether to display embedded element (for post types: audio, youtube, vimeo) or Featured Image on home page"
          options:
            - name: "Featured Image"
              value: "featimg"
            - name: "Embedded Element"
              value: "iframe"
      - name: "vimeo-embed"
        field:
          element: "text"
          label: "Vimeo Embedding Code"
          help: "Set post type to vimeo in order for this to work"
      - name: "gallery-id"
        field:
          element: "text"
          label: "Gallery ID"
          help: "ID of the gallery defined within _data/galleries.yml - use include in content to use"
      - name: "audio-embed"
        field:
          element: "text"
          label: "Audio Embedding Code"
          help: "Set post type to audio in order for this to work"
      - name: "yt-video-id"
        field:
          element: "text"
          label: "YouTube Video ID"
          help: "Set post type to youtube in order for this to work. Do not set featured image, as the youtube video thumbnail will be used"
          type: "text"
